services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: mydb
    ports:
      - "3344:3306"
    volumes:
      - db_data:/var/lib/mysql

  cache:
    image: redis:7.0
    restart: always
    ports:
      - "6380:6379"

volumes:
  db_data: